### ISSUE TITLE
Logging out in the Nether causes the whole game to crash and makes the server inaccessible

### ISSUE THREAD

**Issue by ThatAlecs** [Moresteck/Project-Poseidon-Uberbukkit#26]
Hello everyone,
I run a server on Beta 1.1_02 using Poseidon and this error happens when you log out in the Nether and then log in the server again:

![image](https://github.com/RhysB/Project-Poseidon/assets/41908942/4747fbab-1018-4e7d-a1a1-eabeff586329)

This absolutely prevents the player from logging in the server **until the server owner/admin deletes their player data file, which resets all their data and progress on the server**
When you try to log in the server while in the Nether, Minecraft will hang and then crash after a few minutes.

The steps to reproduce this bug are very simple:

1. Run a Beta 1.1_02 server using Project Poseidon
2. Get to the Nether
3. Log out
4. Try to log back in

**Comment by Moresteck** [comment]
Not a server issue. Add `-Djava.util.Arrays.useLegacyMergeSort=true` to JVM arguments in your launcher, or also Betacraft launcher has this fixed by default

**Comment by ThatAlecs** [comment]
Thanks for the quick response. I'll make sure to tell my players that.
